export async function exportReportPDF({
  shopName,
  dateRange,
  trendData,
  topProducts,
  categories
}: {
  shopName: string;
  dateRange: string;
  trendData: any[];
  topProducts: any[];
  categories: any[];
}) {
  // Dynamically import jspdf and autotable to avoid Webpack 5 client-bundle chunking issues
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF() as any;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text('Business Performance Report', 14, 22);

  // Shop Info & Date
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Store: ${shopName || 'Vyapar Sarthi'}`, 14, 32);
  doc.text(`Date Range: ${dateRange}`, 14, 38);

  // 1. Sales Trend Table
  doc.setFontSize(14);
  doc.setTextColor(40);
  doc.text('Sales & Profit Trend', 14, 52);

  const trendRows = trendData.map((d: any) => [
    d.fullDate,
    `Rs. ${d.sales.toLocaleString('en-IN')}`,
    `Rs. ${d.profit.toLocaleString('en-IN')}`
  ]);

  autoTable(doc, {
    startY: 58,
    head: [['Date', 'Sales', 'Profit']],
    body: trendRows,
    theme: 'grid',
    headStyles: { fillColor: [16, 185, 129] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // 2. Top Products
  const finalY1 = doc.lastAutoTable?.finalY || 60;
  doc.text('Top Selling Products', 14, finalY1 + 14);

  const productRows = topProducts.map((p: any, i: number) => [
    `#${i + 1}`,
    p.name,
    p.category,
    `Rs. ${p.value?.toLocaleString('en-IN') ?? 0}`,
    `${p.qty ?? 0} units`
  ]);

  autoTable(doc, {
    startY: finalY1 + 20,
    head: [['Rank', 'Product Name', 'Category', 'Revenue', 'Quantity Sold']],
    body: productRows,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
  });

  // 3. Category Performance
  const finalY2 = doc.lastAutoTable?.finalY || 100;
  doc.text('Category Performance', 14, finalY2 + 14);

  const categoryRows = categories.map((c: any) => [
    c.name,
    `Rs. ${c.value?.toLocaleString('en-IN') ?? 0}`,
    `${c.qty ?? 0} items`,
    `${c.percentage ?? 0}%`
  ]);

  autoTable(doc, {
    startY: finalY2 + 20,
    head: [['Category', 'Revenue', 'Quantity', 'Share %']],
    body: categoryRows,
    theme: 'grid',
    headStyles: { fillColor: [245, 158, 11] },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by Vyapar Sarthi on ${new Date().toLocaleString()}`,
      14,
      doc.internal.pageSize.height - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.width - 25,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  doc.save(`Business_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
